# Generated by Django 6.0.5 on 2026-06-28 14:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('SUCCESS', 'success'), ('FAILED', 'failure')], default='PENDING', max_length=20)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'deposit'), ('BUY_DATA', 'data plan'), ('BUY_AIRTIME', 'airtime')], max_length=40)),
                ('references', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('telecom_providers', models.CharField(blank=True, choices=[('MTN', 'mtn network'), ('AIRTEL', 'airtel network'), ('GLO', 'glo network'), ('9MOBIL', '9mobile network')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
        ),
    ]
