# Generated by Django 6.0.5 on 2026-07-04 20:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_url',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
