# Generated by Django 6.0.5 on 2026-07-04 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_payment_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='references',
            new_name='reference',
        ),
    ]
