# Generated by Django 6.0.5 on 2026-07-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rename_references_transaction_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
