# Generated by Django 6.0.5 on 2026-07-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_payment_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='telecom_providers',
            new_name='telecom_provider',
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
