# Generated by Django 6.0.5 on 2026-07-19 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_rename_telecom_providers_transaction_telecom_provider_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='telecom_provider',
            new_name='telecom_providers',
        ),
    ]
