# Generated by Django 6.0.5 on 2026-07-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='account_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='account_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='bank_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wallet',
            name='provider_reference',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
