# Generated by Django 6.0.5 on 2026-07-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet_account_name_wallet_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='deposit_provider_reference',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
