# Generated by Django 6.0.5 on 2026-09-05 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_wallet_deposit_provider_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='deposit_provider_reference',
        ),
    ]
