# Generated by Django 6.0.5 on 2026-09-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('PROVIDER_CONTRACT_CHANGED', 'Provider contract changed'), ('DATABASE_UNAVAILABLE', 'Database unavailable'), ('SUSPICIOUS_ACTIVITY', 'Suspicious activity')], max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('CRITICAL', 'critical'), ('WARNING', 'warning')], default='CRITICAL', max_length=30)),
                ('status', models.CharField(choices=[('OPEN', 'open'), ('RESOLVED', 'resolved')], default='OPEN', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
