# Generated by Django 6.0.5 on 2026-09-27 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('CRITICAL', 'critical'), ('WARNING', 'warning')], default='WARNING', max_length=30),
        ),
    ]
