# Generated by Django 6.0.5 on 2026-09-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_alert_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('PROVIDER_CONTRACT_CHANGED', 'Provider contract changed'), ('DATABASE_UNAVAILABLE', 'Database unavailable'), ('SUSPICIOUS_ACTIVITY', 'Suspicious activity'), ('PROVIDER_RESPONSE_UNEXPECTED', 'provider response unexpected')], max_length=50),
        ),
    ]
